name: Setup NodeJS

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  nodejs-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - run: npm version
